name: Build and Release WoW Addon

on:
  release:
    types: [created]  # Runs only when a new release is published

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'
          
      - name: Extract version from release
        id: get_version
        run: |
          echo "VERSION=${{ github.event.release.tag_name }}" >> $GITHUB_OUTPUT

      - name: Build addon zip
        run: |
          mkdir -p output
          python3 wowaddon.py --version=classic --dst=output zip

      - name: Rename zip file with release version
        run: |
          mv output/Restocker-SOD-*.zip output/Restocker-SOD-${{ steps.get_version.outputs.VERSION }}.zip

      - name: Upload release asset
        uses: softprops/action-gh-release@v2
        with:
          files: output/Restocker-SOD-${{ steps.get_version.outputs.VERSION }}.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
